# Generated by Django 6.0.6 on 2026-07-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='points_cost',
            field=models.PositiveIntegerField(blank=True, help_text='Loyalty points a customer can redeem for this item; blank = not redeemable', null=True),
        ),
    ]
