# Generated by Django 6.0.6 on 2026-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='For WhatsApp alerts (low stock, daily summary, etc.)', max_length=20),
        ),
    ]
