# Generated by Django 6.0.6 on 2026-07-14 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0002_menuitem_points_cost'),
        ('pos', '0002_order_customer'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_id'), name='unique_order_client_id_per_cafe'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_id'), name='unique_order_item_client_id_per_cafe'),
        ),
    ]
