# Generated by Django 6.0.6 on 2026-07-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_refund'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shifts.shift'),
        ),
    ]
